name: Test
on:
  pull_request:
    branches:
      - main  # Pre-merge validation
  merge_group:
    branches:
      - main  # Merge queue validation

permissions:
  contents: read

jobs:
  # Test the check-paths action
  check-paths:
    runs-on: ubuntu-latest
    outputs:
      go-lint-changed:    ${{ steps.go-lint.outputs.changed }}
      go-test-changed:    ${{ steps.go-test.outputs.changed }}
      k8s-lint-changed:   ${{ steps.k8s-lint.outputs.changed }}
      ruby-lint-changed:  ${{ steps.ruby-lint.outputs.changed }}
      shellcheck-changed: ${{ steps.shellcheck.outputs.changed }}
      terraform-changed:  ${{ steps.terraform.outputs.changed }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Check go-lint
        id: go-lint
        uses: ./check-paths
        with:
          paths: |
            go-lint/**
      - name: Check go-test
        id: go-test
        uses: ./check-paths
        with:
          paths: |
            go-test/**
      - name: Check k8s-lint
        id: k8s-lint
        uses: ./check-paths
        with:
          paths: |
            k8s-lint/**
      - name: Check ruby-lint
        id: ruby-lint
        uses: ./check-paths
        with:
          paths: |
            ruby-lint/**
      - name: Check shellcheck
        id: shellcheck
        uses: ./check-paths
        with:
          paths: |
            shellcheck/**
      - name: Check terraform
        id: terraform
        uses: ./check-paths
        with:
          paths: |
            terraform/**

  # Test the go-lint action
  go-lint:
    needs: check-paths
    if: needs.check-paths.outputs.go-lint-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./go-lint
        with:
          path: ./go-lint/test

  # Test the go-test action
  go-test:
    needs: check-paths
    if: needs.check-paths.outputs.go-test-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - id: test
        uses: ./go-test
        with:
          path: ./go-test/test
      - name: Upload Test Report
        uses: actions/upload-artifact@v7
        with:
          name: Coverage Report
          path: ./go-test/test/${{ steps.test.outputs.coverage_report_file }}

  # Test the go-build action
  k8s-lint:
    needs: check-paths
    if: needs.check-paths.outputs.k8s-lint-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./k8s-lint
        with:
          path: ./k8s-lint/test
          enable_kubeval: 'true'
          enable_kubescore: 'false'

  # Test the ruby-lint action
  ruby-lint:
    needs: check-paths
    if: needs.check-paths.outputs.ruby-lint-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./ruby-lint
        with:
          path: ./ruby-lint/test

  # Test the shellcheck action
  shellcheck:
    needs: check-paths
    if: needs.check-paths.outputs.shellcheck-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./shellcheck
        with:
          path: ./shellcheck/test

  # Test the terraform action
  terraform:
    needs: check-paths
    if: needs.check-paths.outputs.terraform-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./terraform
        with:
          path: ./terraform/test
          args: validate
